[mypy]
python_version = 3.7

[mypy-auth0.test.*,auth0.test_async.*]
ignore_errors = True

[mypy-auth0.management.*]
ignore_errors = True
